version: 1
formatters:
  simple:
    format: "[%(asctime)s] %(levelname)s %(name)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

loggers:
  contrib_metrics:
    level: INFO
    handlers: [console]
    propagate: False

root:
  level: WARNING
  handlers: [console]
